[build]
  base = "/"
  publish = "dist/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "16.13.1"
  VITE_APP_SEED_FAKE_DATA = "true"
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


